{% set version = "3.8.0" %}

package:
  name: arpack-suite
  version: {{ version }}

source:
  fn: arpack-{{ version }}.tar.gz
  url: https://github.com/opencollab/arpack-ng/archive/{{ version }}.tar.gz
  sha256: ada5aeb3878874383307239c9235b716a8a170c6d096a6625bfd529844df003d

build:
  number: 0

outputs:
  - name: arpack
    script: build-no-mpi.sh  # [not win]
    script: bld-no-mpi.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('arpack', max_pin='x.x') }}
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('fortran') }}  # [unix]
        - {{ compiler('c') }}  # [unix]
        - {{ compiler('cxx') }}  # [unix]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]
      host:
        - libblas
        - liblapack
    test:
      commands:
        - test -f ${PREFIX}/lib/libarpack.a  # [unix]
        - test -f ${PREFIX}/lib/libarpack${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/include/arpack/arpack.hpp  # [unix]
        - if not exist %PREFIX%\\Library\\mingw-w64\\lib\\libarpack.a exit 1  # [win]
        - if not exist %PREFIX%\\Library\\mingw-w64\\lib\\libarpack.dll.a exit 1  # [win]
        - if not exist %PREFIX%\\Library\\mingw-w64\\bin\\libarpack.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\mingw-w64\\include\\arpack\\arpack.hpp exit 1  # [win]

  - name: arpack-mpi
    script: build-mpi.sh  # [not win]
    build:
      skip: true  # [win or (osx and arm64)]
      run_exports:
        - {{ pin_subpackage('arpack-mpi', max_pin='x.x') }}
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('fortran') }}  # [unix]
        - {{ compiler('c') }}  # [unix]
        - {{ compiler('cxx') }}  # [unix]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]
      host:
        - libblas
        - liblapack
        - openmpi  # [unix]
    test:
      commands:
        - test -f ${PREFIX}/lib/libarpack.a  # [unix]
        - test -f ${PREFIX}/lib/libparpack.a  # [unix]
        - test -f ${PREFIX}/lib/libarpack${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/libparpack${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/include/arpack/arpack.hpp  # [unix]

about:
  home: https://github.com/opencollab/arpack-ng
  license: BSD 3-Clause
  license_file: COPYING
  summary: Fortran77 subroutines designed to solve large scale eigenvalue problems

extra:
  recipe-maintainers:
    - jschueller
    - mrakitin
