# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortran
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fort

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "j1R7+OOd4IPq6l0ICFbWKMwjKfKNNUr3bLV3HmSvgsX0Qviibd9c2BWu7v2//ZWIrPr8qRoZDxSTWAxyEhwPFwWdunJG8/gbyeU7H0/gzPeC8LoGHYyXdY1uzJWsZedDlUZtCtpIid/HJPgc8aa9nWaxYE7Av8HqKj+YXp/glFWLgKZulU/myR+zd3Ur8jdaMHHIAwZXYnFQacSlBIjKXOqnA5yWX+XYO+Xztlr7jANJGfzReVnyMW4bvIZ38jOFLQOtxZru1ErM65CokGVeXAGkitrirZroWOHjNQV3iL88nZGbka7fph34enZIJy21KsvR+A4YrW1EfV65aAZ/7bmbGUb+2BOtIBozxnTJ7QJnhtKPbgODs9l3EFz6bkH+5BDVpMDqes+1At40AufKX4ELyuzosB5N2IeVv8yIMW9AGAEEV/d1v3Pzr/QTT8V8Solb//sIRAIm1O0IybCBAJjAv1ZppnfPHHZo8zXS/4zAVZMG1QxYyJw7T5KuETPSuD3eeOhyGqUWbJzSzeim1PAk0w4wZ1f3Hxz+gg+yVGXYrs32Ch+Dty4HC4Waxa9/Hqp/IxLj7Vh9Y3B+4v3LpYsqPZ/iwpr5b2hg27S5NCdZnNeOn0FkrcgJgaTozqEwPbhMavsdS3M1CbeS/Tn1wQLxAAUseMXnG6T0LedB2wU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml