appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: j1R7+OOd4IPq6l0ICFbWKMwjKfKNNUr3bLV3HmSvgsX0Qviibd9c2BWu7v2//ZWIrPr8qRoZDxSTWAxyEhwPFwWdunJG8/gbyeU7H0/gzPeC8LoGHYyXdY1uzJWsZedDlUZtCtpIid/HJPgc8aa9nWaxYE7Av8HqKj+YXp/glFWLgKZulU/myR+zd3Ur8jdaMHHIAwZXYnFQacSlBIjKXOqnA5yWX+XYO+Xztlr7jANJGfzReVnyMW4bvIZ38jOFLQOtxZru1ErM65CokGVeXAGkitrirZroWOHjNQV3iL88nZGbka7fph34enZIJy21KsvR+A4YrW1EfV65aAZ/7bmbGUb+2BOtIBozxnTJ7QJnhtKPbgODs9l3EFz6bkH+5BDVpMDqes+1At40AufKX4ELyuzosB5N2IeVv8yIMW9AGAEEV/d1v3Pzr/QTT8V8Solb//sIRAIm1O0IybCBAJjAv1ZppnfPHHZo8zXS/4zAVZMG1QxYyJw7T5KuETPSuD3eeOhyGqUWbJzSzeim1PAk0w4wZ1f3Hxz+gg+yVGXYrs32Ch+Dty4HC4Waxa9/Hqp/IxLj7Vh9Y3B+4v3LpYsqPZ/iwpr5b2hg27S5NCdZnNeOn0FkrcgJgaTozqEwPbhMavsdS3M1CbeS/Tn1wQLxAAUseMXnG6T0LedB2wU=}
provider:
  win: azure
  linux_ppc64le: azure
